import type { ArchitectureReportMetadata } from "./architectureReportMetadata.js";

export function formatArchitectureReportMetadata(
  metadata: ArchitectureReportMetadata,
): string {
  return [
    `Title: ${metadata.title}`,
    `Generated By: ${metadata.generatedBy}`,
    `Format: ${metadata.format}`,
    `Version: ${metadata.version}`,
  ].join("\n");
}